# Generated by Django 5.0.7 on 2024-08-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('working_hours', models.CharField(choices=[('08:00-12:00', '08:00-12:00'), ('12:00-16:00', '12:00-16:00'), ('16:00-20:00', '16:00-20:00')], default='08:00-12:00', max_length=11)),
                ('description', models.TextField()),
                ('photo', models.ImageField(default='images/doctors/default.jpg', upload_to='images/clinics')),
                ('doctors', models.ManyToManyField(to='doctors.doctor')),
            ],
        ),
    ]
