# Generated by Django 5.0.7 on 2024-08-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(default=None, to='doctors.doctor'),
        ),
    ]
