# Generated by Django 5.0.6 on 2024-08-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_profile_blood_pressure_profile_lab_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
