# Generated by Django 5.0.6 on 2024-08-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='other_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
