# Generated by Django 5.0.6 on 2024-08-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_profile_other_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lab_results',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pulse',
        ),
    ]
