# Generated by Django 5.0.7 on 2024-08-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Oncology', 'Oncology'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology'), ('Surgery', 'Surgery'), ('Orthopedics', 'Orthopedics'), ('Internal Medicine', 'Internal Medicine'), ('Gastroenterology', 'Gastroenterology'), ('Endocrinology', 'Endocrinology'), ('Rheumatology', 'Rheumatology'), ('Urology', 'Urology'), ('Pulmonology', 'Pulmonology'), ('Hematology', 'Hematology'), ('Nephrology', 'Nephrology'), ('Infectious Diseases', 'Infectious Diseases'), ('Allergy and Immunology', 'Allergy and Immunology'), ('Geriatrics', 'Geriatrics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology')], max_length=50)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='doctor_photos/')),
            ],
        ),
    ]
