# Generated by Django 5.0.7 on 2024-08-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Oncology', 'Oncology'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology'), ('Surgery', 'Surgery'), ('Orthopedics', 'Orthopedics'), ('Internal Medicine', 'Internal Medicine'), ('Gastroenterology', 'Gastroenterology'), ('Endocrinology', 'Endocrinology'), ('Rheumatology', 'Rheumatology'), ('Urology', 'Urology'), ('Pulmonology', 'Pulmonology'), ('Hematology', 'Hematology'), ('Nephrology', 'Nephrology'), ('Infectious Diseases', 'Infectious Diseases'), ('Allergy and Immunology', 'Allergy and Immunology'), ('Geriatrics', 'Geriatrics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology')], max_length=50),
        ),
    ]
