# Generated by Django 5.0.7 on 2024-08-07 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_alter_clinic_working_hours'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('8am', '8 AM'), ('9am', '9 AM'), ('10am', '10 AM'), ('11am', '11 AM'), ('12pm', '12 PM'), ('1pm', '1 PM'), ('2pm', '2 PM'), ('3pm', '3 PM'), ('4pm', '4 PM'), ('5pm', '5 PM'), ('6pm', '6 PM'), ('7pm', '7 PM'), ('8pm', '8 PM'), ('9pm', '9 PM'), ('10pm', '10 PM'), ('11pm', '11 PM')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
