# Generated by Django 5.0.7 on 2024-08-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='work_hours',
            field=models.CharField(choices=[('07:00 - 03:00 ', '07:00 AM - 03:00 PM'), ('03:00 - 11:00', '03:00 PM - 11:00 AM'), ('11:00 - 07:00', '11:00 PM - 07:00 AM')], max_length=100),
        ),
    ]
