# Generated by Django 5.0.6 on 2024-08-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0002_alter_clinic_work_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='work_hours',
            field=models.CharField(choices=[('morning', '07:00 AM - 03:00 PM'), ('EVENING', '03:00 PM - 11:00 AM'), ('NIGHT', '11:00 PM - 07:00 AM')], max_length=100),
        ),
    ]
