# Generated by Django 5.0.7 on 2024-08-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "working_hours",
                    models.CharField(
                        choices=[
                            ("09:00-17:00", "09:00 AM - 05:00 PM"),
                            ("08:00-20:00", "08:00 AM - 08:00 PM"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "feature_image",
                    models.ImageField(blank=True, null=True, upload_to="clinics/"),
                ),
                (
                    "doctors",
                    models.ManyToManyField(related_name="clinics", to="doctors.doctor"),
                ),
            ],
        ),
    ]
