# Generated by Django 5.0.7 on 2024-08-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_clinic_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="clinic_logos/default_logo.png",
                null=True,
                upload_to="clinic_logos/",
            ),
        ),
    ]
