# Generated by Django 5.0.7 on 2024-08-05 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0003_alter_clinic_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinic",
            name="working_hours",
        ),
        migrations.AddField(
            model_name="clinic",
            name="closing_time",
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name="clinic",
            name="opening_time",
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
