# Generated by Django 5.0.7 on 2024-08-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0004_remove_clinic_working_hours_clinic_closing_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinic",
            name="logo",
        ),
        migrations.AlterField(
            model_name="clinic",
            name="feature_image",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
