# Generated by Django 5.0.7 on 2024-08-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0005_remove_clinic_logo_alter_clinic_feature_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="clinic_logos/"),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="feature_image",
            field=models.ImageField(blank=True, null=True, upload_to="clinics/"),
        ),
    ]
