# Generated by Django 5.0.7 on 2024-08-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0006_clinic_logo_alter_clinic_feature_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinic",
            name="logo",
        ),
    ]
