# Generated by Django 5.0.7 on 2024-08-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='workingHours',
            field=models.CharField(max_length=64),
        ),
    ]
