# Generated by Django 5.0.7 on 2024-08-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('working_hours', models.CharField(choices=[('9am-5pm', '9 AM - 5 PM'), ('10am-6pm', '10 AM - 6 PM')], max_length=20)),
                ('feature_image', models.ImageField(upload_to='clinic_images/')),
                ('doctors', models.ManyToManyField(to='doctors.doctor')),
            ],
        ),
    ]
