# Generated by Django 5.0.7 on 2024-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='working_hours',
            field=models.CharField(choices=[('8am-4pm', '8 AM - 4 PM'), ('4pm-11pm', '4 AM - 11 PM')], max_length=20),
        ),
    ]
