# Generated by Django 5.0.7 on 2024-08-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_date_of_birth_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
