# Generated by Django 5.0.7 on 2024-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('Pediatrics', 'Pediatrics'), ('Internal Medicine', 'Internal Medicine'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Ophthalmology', 'Ophthalmology'), ('X_Ray Place', 'X-Ray Place'), ('Bone and Joint Surgery', 'Bone and Joint Surgery'), ('Neurology', 'Neurology'), ('General Surgery', 'General Surgery')], max_length=255)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(default='images/doctor/default.png', upload_to='images/doctoor/')),
            ],
        ),
    ]
