# Generated by Django 5.0.7 on 2024-08-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('GP', 'General Practice'), ('CA', 'Cardiology'), ('DE', 'Dermatology'), ('NE', 'Neurology'), ('PE', 'Pediatrics'), ('OR', 'Orthopedics')], default='GP', max_length=2)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(default='images/doctors/default.jpg', upload_to='images/doctors')),
            ],
        ),
    ]
