# Generated by Django 5.0.7 on 2024-08-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('specialization', models.CharField(max_length=128)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(default='images/avtars/avatar.png', upload_to='images/avatars/')),
            ],
        ),
    ]
