# Generated by Django 4.2.13 on 2024-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("specilaization", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                (
                    "photo",
                    models.ImageField(
                        default="images/default.svg", upload_to="images/"
                    ),
                ),
            ],
        ),
    ]
