# Generated by Django 4.2.13 on 2024-08-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_doctor_country_doctor_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor", name="facebook_link", field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="instagram_link",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="doctor", name="x_link", field=models.URLField(null=True),
        ),
    ]
