# Generated by Django 5.0.7 on 2024-08-07 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0002_clinic_doctors_alter_clinic_workinghours'),
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('TimeSlot', models.TimeField(choices=[(1, '8:00 - 8:30'), (2, '8:30 - 9:00'), (3, '9:00 - 9:30'), (4, '9:30 - 10:00'), (5, '10:00 - 10:30'), (6, '10:30 - 11:00'), (7, '11:00 - 11:30'), (8, '11:30 - 12:00'), (9, '12:00 - 12:30'), (10, '12:30 - 13:00'), (11, '13:00 - 13:30'), (12, '13:30 - 14:00'), (13, '14:00 - 14:30'), (14, '14:30 - 15:00'), (15, '15:00 - 15:30'), (16, '15:30 - 16:00'), (17, '16:00 - 16:30'), (18, '16:30 - 17:00'), (19, '17:00 - 17:30'), (20, '17:30 - 18:00')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
