# Generated by Django 5.0.7 on 2024-08-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('available_appointments', models.TextField(default='No appointments available')),
                ('feature_image', models.ImageField(upload_to='clinic_images/')),
                ('doctors', models.ManyToManyField(related_name='clinics', to='doctors.doctor')),
            ],
        ),
    ]
