# Generated by Django 5.0.7 on 2024-08-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='closing_time',
            new_name='working_hours_end',
        ),
        migrations.RenameField(
            model_name='clinic',
            old_name='opening_time',
            new_name='working_hours_start',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='available_appointments',
        ),
    ]
