# Generated by Django 5.0.7 on 2024-08-06 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_rename_closing_time_clinic_working_hours_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='working_hours_end',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='working_hours_start',
        ),
        migrations.AddField(
            model_name='clinic',
            name='closing_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='clinic',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='clinics/'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
