# Generated by Django 5.0.7 on 2024-08-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_remove_clinic_working_hours_end_and_more'),
        ('doctors', '0002_alter_doctor_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(to='doctors.doctor'),
        ),
    ]
