# Generated by Django 5.0.7 on 2024-08-08 07:16

import doctors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1024)),
                ('specialization', models.CharField(choices=[('DENT', 'Dentistry'), ('CARD', 'Cardiology'), ('EMT', 'EMT'), ('DERM', 'Dermatology'), ('ORTH', 'Orthopedics'), ('NEUR', 'Neurology'), ('PEDI', 'Pediatric')], default=doctors.models.Doctor.Specialization, max_length=64)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
