# Generated by Django 5.0.6 on 2024-08-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('specialization', models.CharField(choices=[(1, 'Dentistry'), (2, 'Cardiology'), (3, 'EMT'), (4, 'Dermatology'), (5, 'Orthopedics'), (6, 'Neurology'), (7, 'Pediatric')], max_length=1024)),
                ('bio', models.TextField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
