# Generated by Django 5.0.7 on 2024-08-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('CARD', 'Cardiology'), ('DERM', 'Dermatology'), ('NEUR', 'Neurology'), ('ORTH', 'Orthopedics'), ('PEDI', 'Pediatrics'), ('GAST', 'Gastroenterology'), ('OBGY', 'Obstetrics and Gynecology'), ('ONCO', 'Oncology'), ('PSYC', 'Psychiatry'), ('ENDO', 'Endocrinology'), ('UROL', 'Urology'), ('OPHT', 'Ophthalmology')], max_length=4)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(default='images/default.jpg', upload_to='images/')),
            ],
        ),
    ]
