# Generated by Django 5.0.7 on 2024-08-07 22:05

import doctors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_specialization_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('DENT', 'Dentistry'), ('CARD', 'Cardiology'), ('EMT', 'EMT'), ('DERM', 'Dermatology'), ('ORTH', 'Orthopedics'), ('NEUR', 'Neurology'), ('PEDI', 'Pediatric')], default=doctors.models.Doctor.Specialization, max_length=64),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
