# Generated by Django 5.0.7 on 2024-08-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("CARDIOLOGY", "Cardiology"),
                            ("DERMATOLOGY", "Dermatology"),
                            ("NEUROLOGY", "Neurology"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="doctors/"),
                ),
            ],
        ),
    ]
