# Generated by Django 5.0.7 on 2024-08-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_doctor_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="doctor_profiles/default_profile.png",
                null=True,
                upload_to="doctor_profiles/",
            ),
        ),
    ]
