# Generated by Django 5.0.7 on 2024-08-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_alter_doctor_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
