# Generated by Django 5.0.7 on 2024-08-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_alter_doctor_photo_alter_doctor_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="profile_picture",
        ),
    ]
