# Generated by Django 5.0.7 on 2024-08-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0005_remove_doctor_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="doctors/"),
        ),
    ]
