# Generated by Django 5.0.7 on 2024-08-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('cardiologist', 'Cardiologist'), ('neurologist', 'Neurologist'), ('dermatologist', 'Dermatologist'), ('oncologist', 'Oncologist'), ('pediatrician', 'Pediatrician'), ('psychiatrist', 'Psychiatrist'), ('gynecologist', 'Gynecologist'), ('orthopedist', 'Orthopedist'), ('urologist', 'Urologist'), ('endocrinologist', 'Endocrinologist')], max_length=50)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='doctor_photos/')),
            ],
        ),
    ]
