# Generated by Django 5.0.6 on 2024-08-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("cardiology", "Cardiology"),
                            ("neurology", "Neurology"),
                            ("pediatrics", "Pediatrics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bio", models.TextField()),
                ("photo", models.ImageField(upload_to="doctor_photos/")),
            ],
        ),
    ]
